"""Shared AI interface strings."""
WORDS = {
 'en': dict(title='AI assistant', depth='Depth', device='Device', speed='Speed',
           instant='Instant', fast='Fast', normal='Normal', analyze='Refresh', step='One step',
           auto='Auto run', stop='Stop', ready='Ready', loading='Thinking…', stopped='Paused',
           terminal='Game over', directions=('↑ Up', '→ Right', '↓ Down', '← Left'), invalid='—',
           gpu_unavailable='GPU unavailable. A CUDA-capable NVIDIA GPU and compatible PyTorch/driver are required. Select CPU to continue.',
           gpu_memory='GPU memory is full. Select a lower depth or CPU, then retry.',
           cpu_memory='System memory is exhausted. Close unused game windows or applications, then restart this game.',
           gpu_error='GPU failed. Select CPU or check your GPU driver, then retry.',
           model_missing='Model file is missing. Restore models/latest/best.pt and retry.',
           model_invalid='Model file is damaged or incompatible. Restore the model and retry.',
           runtime_missing='AI runtime is missing or could not load. Reinstall the application.',
           inference_error='Analysis failed. Please retry.'),
 'zh': dict(title='AI 助手', depth='深度', device='计算设备', speed='速度',
           instant='立即', fast='快速', normal='普通', analyze='刷新建议', step='执行一步',
           auto='自动运行', stop='停止', ready='就绪', loading='正在思考…', stopped='已暂停',
           terminal='游戏结束', directions=('↑ 上', '→ 右', '↓ 下', '← 左'), invalid='—',
           gpu_unavailable='GPU 不可用。需要支持 CUDA 的 NVIDIA 显卡及兼容的 PyTorch/驱动。请选择 CPU 继续。',
           gpu_memory='显存不足。请降低深度或切换 CPU 后重试。',
           cpu_memory='系统内存不足。请关闭多余的游戏窗口或其他程序，再重新打开游戏。',
           gpu_error='GPU 运行失败。请切换 CPU，或检查显卡驱动后重试。',
           model_missing='模型文件缺失，请恢复 models/latest/best.pt 后重试。',
           model_invalid='模型文件损坏或不兼容，请恢复模型后重试。',
           runtime_missing='AI 运行库缺失或无法加载，请重新安装程序。',
           inference_error='分析失败，请重试。'),
}
